-- MySQL Script generated by MySQL Workbench
-- sáb 25 feb 2023 13:34:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geniat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geniat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `geniat` ;

-- -----------------------------------------------------
-- Table `geniat`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geniat`.`rol` (
  `idRol` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;

INSERT INTO `rol` (`idRol`, `tipo`) VALUES
(1, 'basico'),
(2, 'medio'),
(3, 'medio alto'),
(4, 'alto medio'),
(5, 'alto');

-- -----------------------------------------------------
-- Table `geniat`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geniat`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `rol_idRol`),
  INDEX `fk_usuario_rol_idx` (`rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_idRol`)
    REFERENCES `geniat`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geniat`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geniat`.`publicacion` (
  `idPublicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPublicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geniat`.`publicacion_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geniat`.`publicacion_has_usuario` (
  `publicacion_idPublicacion` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`publicacion_idPublicacion`, `usuario_idUsuario`),
  INDEX `fk_publicacion_has_usuario_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_publicacion_has_usuario_publicacion1_idx` (`publicacion_idPublicacion` ASC) VISIBLE,
  CONSTRAINT `fk_publicacion_has_usuario_publicacion1`
    FOREIGN KEY (`publicacion_idPublicacion`)
    REFERENCES `geniat`.`publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_publicacion_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `geniat`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
